### ISSUE TITLE
Add to the awesome-graphql list?

### ISSUE THREAD

**Issue by tomhoule** [graphql-rust/graphql-parser#17]
There is a repository to collect projects in the GraphQL ecosystem, and there is already a [rust section](https://github.com/chentsulin/awesome-graphql#lib-rust). Since there are other parsers in the list I think this library has its place, and it would make the Rust section bigger :) I can make the PR if you prefer.

By the way, I am working on the [graphql-client](https://github.com/tomhoule/graphql-client) crate and I am using graphql-parser internally so I'll take this occasion to say thank you!

**Comment by tailhook** [comment]
Sure, feel free to make a PR

**Comment by tomhoule** [comment]
[PR is open](https://github.com/chentsulin/awesome-graphql/pull/366)

**Comment by tomhoule** [comment]
The PR has just been merged, so I'll close this issue :)

**Comment by tailhook** [comment]
Great! Thanks!
