### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by davidpdrsn** [graphql-rust/graphql-parser#18]
Hi 👋

I was just wondering if there are some plans of adding support for [comments in the schema](https://facebook.github.io/graphql/June2018/#sec-Comments)? Currently they just disappear when using [`Document::format`](https://docs.rs/graphql-parser/0.2.2/graphql_parser/schema/struct.Document.html#method.format) because they aren't in AST.

**Comment by tailhook** [comment]
Hi!

No, we have no plans for it. We have AST (abstract syntax tree) here not CST (concrete syntax tree, the one keeping whitespace and comments)

I.e. this parser is not intended for rewriting original graphql query/schema. Formatting is there merely for debugging and perhaps minification (this requires some work though).

On the other hand, we support docstrings.

**Comment by davidpdrsn** [comment]
Alright. Thanks fair game. I'll make do with doc strings 😄
