### ISSUE TITLE
New release on crates.io

### ISSUE THREAD

**Issue by LegNeato** [graphql-rust/graphql-parser#28]
Juniper would like to use the borrowed AST on master. What is outstanding to cut a new release?

**Comment by LegNeato** [comment]
Probably need to figure out https://github.com/graphql-rust/graphql-parser/pull/27

**Comment by tailhook** [comment]
> Juniper would like to use the borrowed AST on master. What is outstanding to cut a new release?

If you've tried it and it works then probably nothing. 

I'm not sure if #27 is possible to fix :(

**Comment by LegNeato** [comment]
@tailhook any chance we can get a release soon?

**Comment by tailhook** [comment]
Released 0.3.0
