### ISSUE TITLE
format broken for nameless operation with variables

### ISSUE THREAD

**Issue by timsuchanek** [graphql-rust/graphql-parser#46]
Formatting this query:
```graphql
query ($first: Int, $second: Int) {
  field1(first: $first)
  field2(second: $second)
}
```
returns this result:
```graphql
query {
  field1(first: $first)
  field2(second: $second)
}
```

Test code:
```rust
use graphql_parser::parse_query;

fn main() {
    let ast = parse_query::<&str>(
        "\
query ($first: Int, $second: Int) {
  field1(first: $first)
  field2(second: $second)
}",
    )
    .unwrap();
    // Format canonical representation
    println!("{}", ast);
}
```

And I think the culprit is here: https://github.com/graphql-rust/graphql-parser/blob/master/src/query/format.rs#L156

**Comment by tailhook** [comment]
Hm, I thought this is not allowed syntax (so it's actually a parser which is broken). Is it?

**Comment by timsuchanek** [comment]
Yes could also be the parser. So graphql-js allows it and we have real world application with that use-case, which already runs fine on graphql-js.

**Comment by timsuchanek** [comment]
Where would you fix that? If you give me a hint in the code, I could also have a look.

**Comment by tailhook** [comment]
Okay, looks like I'm wrong. So initially pointed line is the place to fix (probably by just moving closing brace). But please also add a test. Thanks!

**Comment by timsuchanek** [comment]
Sounds good! PR is ready :)
