### ISSUE TITLE
Time for a 0.3.1 release?

### ISSUE THREAD

**Issue by leoyvens** [graphql-rust/graphql-parser#50]
It's been a year since the last release, and there have been a few patches since. If you could cut a new release that would be great!

**Comment by mathstuf** [comment]
This would make `Document::into_static` available which is sorely needed to actually use in anything that doesn't already have borrows flowing through it.

**Comment by tailhook** [comment]
Just published 0.4.0. Sorry for the delay.

_It couldn't be 0.3.1 since we have structured with public fields and every new field is a breaking change (in this case we at least added `repeatable`)._
