### ISSUE TITLE
Release new version that includes the `combine` version bump?

### ISSUE THREAD

**Issue by vorporeal** [graphql-rust/graphql-parser#78]
Would be nice for this crate to publish an updated version that includes the `combine` major version bump, so that it can get picked up by dependencies and utilized by downstream consumers.

While we could use a `[patch]` directive in our own Cargo.toml to pull in this crate at the commit that introduced the version bump, that shouldn't be required of all applications.

**Comment by vorporeal** [comment]
@tomhoule Apologies for directly mentioning you, but noticed that you've been active in the graphql-client repo, and this one seems to be generally pretty dead - wanted to make sure _someone_ who owns graphql-rust saw this issue.

**Comment by tomhoule** [comment]
Hi @vorporeal! I'm not an owner on this repo / the crate, but I'll try to see who I can contact.

**Comment by LegNeato** [comment]
@tailhook Are you able to cut a new release?

**Comment by github2023spring** [comment]
We also have similar request here. Our build system does not allow us to access public network during build time. So, we cannot download it from github using patch.

**Comment by dotansimha** [comment]
If anyone needs the latest version, see https://github.com/graphql-hive/graphql-parser-hive-fork?tab=readme-ov-file#graphql-parser-fork for a published the latest version. Using Git for deps is great, but Crates.io doesn't allow publishing Crates with Git deps so we had to fork and publish it.

**Comment by tomhoule** [comment]
Hi @dotansimha , if you are planning to maintain the fork, we could switch graphql-client to use it.

**Comment by dotansimha** [comment]
> Hi @dotansimha , if you are planning to maintain the fork, we could switch graphql-client to use it.

I do plan to maintain this fork, as we are using it in GraphQL-Hive. 
We used it from Git for some time, but it blocked us from publishing to Crates, that's why we needed a fork. 

My preference of course would be to avoid forking, but it seems like the repo is not well maintained and did not cut a release in the past 3 years. Ideally, if this repo will become more active and will cut frequent releases, we will reconsider our support in our fork and will look to merge the work with the main repo.

**Comment by LegNeato** [comment]
While I have access to the repo, I do not have access to crates.io. Only @tailhook does afaik.

**Comment by LegNeato** [comment]
(I'd love to get access and keep the project moving along with more maintainers and more releases)

**Comment by dotansimha** [comment]
@tailhook can we please get your help with unblocking releases here?

**Comment by LegNeato** [comment]
I got access, thanks @tailhook !

**Comment by LegNeato** [comment]
It should be released as 0.4.1 now!
