### ISSUE TITLE
Release the change of VariableDefinition to Crate Io

### ISSUE THREAD

**Issue by github2023spring** [graphql-rust/graphql-parser#81]
Hey,

is there a plan to release the newest change into Crate io?

We are not able to directly consume crates due to Network issue. So, wish that it could be release to Crate Io.

**Comment by dotansimha** [comment]
If you need the latest version, see https://github.com/graphql-hive/graphql-parser-hive-fork?tab=readme-ov-file#graphql-parser-fork for a published the latest version. Using Git for deps is great, but Crates.io doesn't allow publishing Crates with Git deps so we had to fork and publish it.

**Comment by LegNeato** [comment]
It should be released as 0.4.1 now!
